# Generated by Django 3.0.8 on 2020-07-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('friendship', '0004_auto_20200719_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user_one_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_two_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='profiles.Profile'),
        ),
    ]
