# Generated by Django 3.0.8 on 2020-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200721_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flag',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=10),
            preserve_default=False,
        ),
    ]
